# Generated by Django 4.2.4 on 2023-08-29 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_contribproject_detail_myproject_detail_skill_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contribproject',
            name='image',
        ),
        migrations.RemoveField(
            model_name='myproject',
            name='image',
        ),
        migrations.AddField(
            model_name='contribproject',
            name='image_profile',
            field=models.ImageField(blank=True, null=True, unique=True, upload_to='media/images/'),
        ),
        migrations.AddField(
            model_name='contribproject',
            name='surl',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='myproject',
            name='image_profile',
            field=models.ImageField(blank=True, null=True, unique=True, upload_to='media/images/'),
        ),
        migrations.AddField(
            model_name='myproject',
            name='surl',
            field=models.URLField(blank=True, null=True),
        ),
    ]
